title: poyopeta.github.io
email: yu-hashimoto[at]eis.t.u-tokyo.ac.jp
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
github_username: poyopeta
domain: poyopeta.github.io
url: https://poyopeta.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
